# Generated by Django 4.1 on 2022-09-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_addquestion_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquestion',
            name='course',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addquestion',
            name='marks',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
