# Generated by Django 4.1 on 2022-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_addquestion_course_addquestion_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='totalmarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='totalquestion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='addquestion',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='addquestion',
            name='marks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
