# Generated by Django 4.0.5 on 2022-09-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='repeatpassword',
        ),
    ]
